# Generated by Django 4.1.7 on 2024-04-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_content_updated_at_alter_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
