# Generated by Django 4.1.7 on 2024-04-19 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_is_single_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='recurrence',
            new_name='recurrence_rules',
        ),
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_rules', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_supprime', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='api.event')),
            ],
        ),
    ]
