# Generated by Django 4.1.7 on 2024-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_content_description_alter_content_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_full_day',
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
