# Generated by Django 4.1.7 on 2023-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='reccurence',
            field=models.CharField(default=['once', 'daily', 'weekly', 'monthly', 'yearly'], max_length=30),
        ),
    ]
