# Generated by Django 4.1.7 on 2023-07-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('duration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='id_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video'),
        ),
    ]
