version: "3"

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: /bin/bash -c "/entrypoint.sh"

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ynF&7vhXMYz3&Uq*kQk&
      MYSQL_DATABASE: planner_ddb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  redis: # Broker
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: /bin/bash -c "/entrypoint.sh"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - backend
      - redis

  celery_beat:
    build: .
    container_name: celery_beat
    command: /bin/bash -c "/entrypoint.sh"
    depends_on:
      - backend
      - redis 
      - celery_worker
    