version: "3"

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ynF&7vhXMYz3&Uq*kQk&
      MYSQL_DATABASE: planner_ddb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     MYSQL_ROOT_PASSWORD: ynF&7vhXMYz3&Uq*kQk&
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
